/* Auto-generated by genmsg_cpp for file /home/skel/roboskel_workspace/sandbox/rn_face/msg/hcma.msg */
#ifndef RN_FACE_MESSAGE_HCMA_H
#define RN_FACE_MESSAGE_HCMA_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "rn_face/hcm.h"

namespace rn_face
{
template <class ContainerAllocator>
struct hcma_ {
  typedef hcma_<ContainerAllocator> Type;

  hcma_()
  : head_co()
  {
  }

  hcma_(const ContainerAllocator& _alloc)
  : head_co(_alloc)
  {
  }

  typedef std::vector< ::rn_face::hcm_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::rn_face::hcm_<ContainerAllocator> >::other >  _head_co_type;
  std::vector< ::rn_face::hcm_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::rn_face::hcm_<ContainerAllocator> >::other >  head_co;


  typedef boost::shared_ptr< ::rn_face::hcma_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rn_face::hcma_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct hcma
typedef  ::rn_face::hcma_<std::allocator<void> > hcma;

typedef boost::shared_ptr< ::rn_face::hcma> hcmaPtr;
typedef boost::shared_ptr< ::rn_face::hcma const> hcmaConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::rn_face::hcma_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::rn_face::hcma_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace rn_face

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::rn_face::hcma_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::rn_face::hcma_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::rn_face::hcma_<ContainerAllocator> > {
  static const char* value() 
  {
    return "5965750697474fb92efa297d80e9d602";
  }

  static const char* value(const  ::rn_face::hcma_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x5965750697474fb9ULL;
  static const uint64_t static_value2 = 0x2efa297d80e9d602ULL;
};

template<class ContainerAllocator>
struct DataType< ::rn_face::hcma_<ContainerAllocator> > {
  static const char* value() 
  {
    return "rn_face/hcma";
  }

  static const char* value(const  ::rn_face::hcma_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::rn_face::hcma_<ContainerAllocator> > {
  static const char* value() 
  {
    return "hcm[] head_co\n\
\n\
================================================================================\n\
MSG: rn_face/hcm\n\
int64 timestamp\n\
int64 id\n\
int8[10] x\n\
int8[10] y\n\
int8[10] z\n\
\n\
";
  }

  static const char* value(const  ::rn_face::hcma_<ContainerAllocator> &) { return value(); } 
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::rn_face::hcma_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.head_co);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct hcma_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rn_face::hcma_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::rn_face::hcma_<ContainerAllocator> & v) 
  {
    s << indent << "head_co[]" << std::endl;
    for (size_t i = 0; i < v.head_co.size(); ++i)
    {
      s << indent << "  head_co[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::rn_face::hcm_<ContainerAllocator> >::stream(s, indent + "    ", v.head_co[i]);
    }
  }
};


} // namespace message_operations
} // namespace ros

#endif // RN_FACE_MESSAGE_HCMA_H

