/* Auto-generated by genmsg_cpp for file /home/skel/roboskel_workspace/sandbox/robot_skel/sdc2130_skel/msg/teleop_skel.msg */
#ifndef SDC2130_SKEL_MESSAGE_TELEOP_SKEL_H
#define SDC2130_SKEL_MESSAGE_TELEOP_SKEL_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "std_msgs/Header.h"

namespace sdc2130_skel
{
template <class ContainerAllocator>
struct teleop_skel_ {
  typedef teleop_skel_<ContainerAllocator> Type;

  teleop_skel_()
  : header()
  , left(0)
  , right(0)
  {
  }

  teleop_skel_(const ContainerAllocator& _alloc)
  : header(_alloc)
  , left(0)
  , right(0)
  {
  }

  typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
   ::std_msgs::Header_<ContainerAllocator>  header;

  typedef int16_t _left_type;
  int16_t left;

  typedef int16_t _right_type;
  int16_t right;


  typedef boost::shared_ptr< ::sdc2130_skel::teleop_skel_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::sdc2130_skel::teleop_skel_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct teleop_skel
typedef  ::sdc2130_skel::teleop_skel_<std::allocator<void> > teleop_skel;

typedef boost::shared_ptr< ::sdc2130_skel::teleop_skel> teleop_skelPtr;
typedef boost::shared_ptr< ::sdc2130_skel::teleop_skel const> teleop_skelConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::sdc2130_skel::teleop_skel_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::sdc2130_skel::teleop_skel_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace sdc2130_skel

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::sdc2130_skel::teleop_skel_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::sdc2130_skel::teleop_skel_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::sdc2130_skel::teleop_skel_<ContainerAllocator> > {
  static const char* value() 
  {
    return "fc27340d1c328ae5b356b2f2a019aa82";
  }

  static const char* value(const  ::sdc2130_skel::teleop_skel_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xfc27340d1c328ae5ULL;
  static const uint64_t static_value2 = 0xb356b2f2a019aa82ULL;
};

template<class ContainerAllocator>
struct DataType< ::sdc2130_skel::teleop_skel_<ContainerAllocator> > {
  static const char* value() 
  {
    return "sdc2130_skel/teleop_skel";
  }

  static const char* value(const  ::sdc2130_skel::teleop_skel_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::sdc2130_skel::teleop_skel_<ContainerAllocator> > {
  static const char* value() 
  {
    return "Header header\n\
int16 left\n\
int16 right\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.secs: seconds (stamp_secs) since epoch\n\
# * stamp.nsecs: nanoseconds since stamp_secs\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
";
  }

  static const char* value(const  ::sdc2130_skel::teleop_skel_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct HasHeader< ::sdc2130_skel::teleop_skel_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct HasHeader< const ::sdc2130_skel::teleop_skel_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::sdc2130_skel::teleop_skel_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.header);
    stream.next(m.left);
    stream.next(m.right);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct teleop_skel_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::sdc2130_skel::teleop_skel_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::sdc2130_skel::teleop_skel_<ContainerAllocator> & v) 
  {
    s << indent << "header: ";
s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "left: ";
    Printer<int16_t>::stream(s, indent + "  ", v.left);
    s << indent << "right: ";
    Printer<int16_t>::stream(s, indent + "  ", v.right);
  }
};


} // namespace message_operations
} // namespace ros

#endif // SDC2130_SKEL_MESSAGE_TELEOP_SKEL_H

